//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab.Database.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int NoteId { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
